# Generated by Django 3.0.7 on 2020-06-19 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categury',
            new_name='Category',
        ),
    ]
